
#!/usr/bin/env python3
"""
Scan a directory for images (png,jpg,jpeg,pdf,svg,eps...) and produce a LaTeX beamer file
with one slide per image. Optionally compile the generated .tex using pdflatex.

Usage:
    python3 make_beamer.py --plots ../plots --out slides.tex
    python3 make_beamer.py --plots ../plots --out slides.tex --compile
"""

import argparse
from pathlib import Path
import re
import subprocess
import sys
import shutil

# --- helpers ---------------------------------------------------------------
IMAGE_EXTS = {'.png', '.jpg', '.jpeg', '.pdf', '.svg', '.eps', '.bmp', '.tiff', '.tif'}


def natural_sort_key(s: str):
    """Return a key for natural/human sorting (numbers numerically)."""
    _nsre = re.compile(r'(\d+)')
    return [int(text) if text.isdigit() else text.lower() for text in re.split(_nsre, s)]


def escape_latex(text: str) -> str:
    """Escape LaTeX-special characters in text used in captions/filenames."""
    # Keep the path separators and characters for \includegraphics, but escape the caption text.
    replacements = {
        '\\': r'\textbackslash{}',
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
    }
    return ''.join(replacements.get(c, c) for c in text)


# --- main logic -----------------------------------------------------------
def build_beamer(tex_path: Path, files, title="Plots presentation", author=None, theme="default"):
    """Write a beamer .tex file with one image per frame."""
    tex_path.parent.mkdir(parents=True, exist_ok=True)
    with tex_path.open("w", encoding="utf-8") as f:
        f.write(r"% Auto-generated by make_beamer.py" + "\n")
        f.write(r"\documentclass{beamer}" + "\n")
        f.write(r"\usepackage{graphicx}" + "\n")
        f.write(r"\usepackage{caption}" + "\n")
        f.write(r"\usepackage{grffile}" + "\n")  # better support for dots/spaces in filenames
        f.write("\n")
        if theme != "default":
            f.write(r"\usetheme{" + theme + "}\n")
        f.write("\n")
        f.write(r"\title{" + escape_latex(title) + "}\n")
        if author:
            f.write(r"\author{" + escape_latex(author) + "}\n")
        f.write(r"\date{\today}" + "\n\n")
        f.write(r"\begin{document}" + "\n\n")

        for p in files:
            # Use the filename as caption (escaped); use relative path as provided
            rel = p.as_posix()
            caption = escape_latex(p.name)
            f.write(r"\begin{frame}[t]" + "\n")
            f.write(r"  \centering" + "\n")
            # scale down very large images but keep aspect ratio
            f.write(rf"  \includegraphics[width=\textwidth]{{{rel}}}" + "\n")
            f.write(rf"  \vspace{{1ex}}\\\footnotesize\texttt{{{caption}}}" + "\n")
            f.write(r"\end{frame}" + "\n\n")

        f.write(r"\end{document}" + "\n")

    print(f"Wrote {tex_path} with {len(files)} slide(s).")


def find_image_files(directory: Path, recursive=False):
    if not directory.exists():
        raise FileNotFoundError(f"Plot directory not found: {directory}")
    if recursive:
        files = [p for p in directory.rglob("*") if p.suffix.lower() in IMAGE_EXTS and p.is_file()]
    else:
        files = [p for p in directory.iterdir() if p.suffix.lower() in IMAGE_EXTS and p.is_file()]
    files.sort(key=lambda p: natural_sort_key(p.name))
    return files


def compile_tex(tex_path: Path, workdir: Path = None, engine="pdflatex"):
    workdir = workdir or tex_path.parent
    engine_path = shutil.which(engine)
    if engine_path is None:
        raise RuntimeError(f"TeX engine '{engine}' not found in PATH.")
    # run twice for correct references (not strictly necessary here but common practice)
    cmd = [engine, "-interaction=nonstopmode", str(tex_path.name)]
    for i in range(2):
        print(f"Running: {' '.join(cmd)} (in {workdir})")
        r = subprocess.run(cmd, cwd=workdir)
        if r.returncode != 0:
            raise RuntimeError(f"{engine} failed (return code {r.returncode}). See output above.")
    print("Compilation finished. PDF is at:", (workdir / tex_path.with_suffix(".pdf").name).resolve())


def main():
    parser = argparse.ArgumentParser(description="Generate a beamer .tex with one image per slide.")
    parser.add_argument("--plots", "-p", type=str, default="../plots", help="Directory containing plots")
    parser.add_argument("--out", "-o", type=str, default="slides.tex", help="Output .tex file path")
    parser.add_argument("--title", type=str, default="Plots presentation", help="Presentation title")
    parser.add_argument("--author", type=str, default=None, help="Author name (optional)")
    parser.add_argument("--recursive", action="store_true", help="Recursively search subdirectories")
    parser.add_argument("--compile", action="store_true", help="Run pdflatex to compile the tex into a PDF")
    parser.add_argument("--engine", type=str, default="pdflatex", help="TeX engine to use for compilation")
    parser.add_argument("--theme", type=str, default="default", help="Beamer theme name (or 'default')")
    args = parser.parse_args()

    plot_dir = Path(args.plots)
    tex_path = Path(args.out)

    files = find_image_files(plot_dir, recursive=args.recursive)
    if not files:
        print(f"No images found in {plot_dir} (extensions: {sorted(IMAGE_EXTS)})")
        sys.exit(1)

    # If output path is outside the plots dir, include images by relative path from output tex directory.
    # To keep things simple we will write the paths exactly as Path.as_posix() so keep the relative relation
    # between tex file and plots directory as you desire.
    build_beamer(tex_path, files, title=args.title, author=args.author, theme=args.theme)

    if args.compile:
        try:
            compile_tex(tex_path, workdir=tex_path.parent, engine=args.engine)
        except Exception as e:
            print("Compilation failed:", e)
            sys.exit(2)


if __name__ == "__main__":
    main()
